### ISSUE TITLE
Diffs of very small images are hard to read (2-up) or unusable (onion skin)

### ISSUE THREAD

**Issue by ChiriVulpes** [desktop/desktop#11404]
### Describe the bug

Diffs of images with very small widths are unreadable for 2-up mode: They cause the "Deleted" and "Added" text to overlap and the file stats to merge together.

![image](https://user-images.githubusercontent.com/6081834/104832929-46009680-58e9-11eb-811a-e6160bf4ee35.png)

The same diffs are entirely unusable in "onion skin" mode: They cause the slider to be way too small to use (it allows you to drag it to the right and then the slider can no longer be moved at all.)

![image](https://user-images.githubusercontent.com/6081834/184073562-eeac6564-a46e-4bf9-b9cf-65349ac261e1.png)

### Version & OS

Version 2.6.2, Windows
...
Version 3.0.5, Windows

### Steps to reproduce the behavior

Add an image with a small width to a repository and look at the diff. To save you some time, here's a couple 16x16 slime sprites:

![slime example](https://user-images.githubusercontent.com/6081834/104832991-c0c9b180-58e9-11eb-9713-55e192127193.png) ![slime example orange](https://user-images.githubusercontent.com/6081834/104833220-2c604e80-58eb-11eb-9499-7e5f510bf831.png)

### Expected behavior

There should be a minimum width on the sides of the diff that prevents any of this overlapping. Here's an example of CSS that could potentially be added to fix this:
```css
/* Fix 2-up image diffs having no minimum size and as a result being incomprehensible */
.panel.image .image-diff-two-up :is(.image-diff-previous, .image-diff-current) {
    min-width: 200px;
}

/* Fix swipe/onion skin image diff slider min-width */
:is(.image-diff-swipe, .image-diff-onion-skin) .slider {
    min-width: 200px;
}
```
Which produces:
![image](https://user-images.githubusercontent.com/6081834/104833169-cc69a800-58ea-11eb-8d6c-5bd59f9c1662.png)

I would assume you would want to do it via variable and stuff, though, so a hardcoded rule like this probably wouldn't work. Just showing that it can be solved without too many CSS changes 😃

**Comment by steveward** [comment]
Thanks for reporting this @ChiriCuddles!

**Comment by ankushduacodes** [comment]
Hi @steveward, I would love to work on this issue. Please let me know if I may.

Thanks!..

**Comment by steveward** [comment]
@ankushduacodes that'd be great! Let us know if you have any questions.

**Comment by ankushduacodes** [comment]
@steveward I am not sure how to reproduce the issue. And the instruction provided in the issue description is not very clear to me.
If you could help me reproduce and where to look for the concerned code that would be awesome.

Thanks!...

**Comment by ChiriVulpes** [comment]
1. Create repository.
2. Add one of those small images to the repository.
3. Commit.
4. Replace the small image with the other one.
5. Look at the diff.

**Comment by ChiriVulpes** [comment]
I've updated this issue with further information and updated suggestions.
- It's not just 2-up that's got issues at diffs this small, Onion Skin is also broken (it actually doesn't even work)
- Updated suggested CSS to also set a minimum slider width in swipe/onion skin modes

I'll also note that when comparing a diff of a small, transparent, white icon, you legitimately just can't see anything in the diff at all (that's also visible in the onion skinning screenshot above). I don't know if that's worth fixing, but I fixed it in my local stylesheet by just getting rid of the tiled background since it doesn't work in my use case (and it's honestly painful on the eyes in dark mode for larger images anyway) and replacing it with the background colour (which is much less likely to be the same as an image I'm working on than pure white)
```css
/* Remove white background behind images in image diff */
:is(.image-diff-onion-skin, .image-diff-swipe) .sizing-container .image-container, .panel.image :is(.image-diff-previous, .image-diff-current) img {
    background-image: none;
    background: var(--background-color) !important;
}
```
