### ISSUE TITLE
Lefthook Git hook returning executable file not found in %PATH%

### ISSUE THREAD

**Issue by bbodenmiller** [desktop/desktop#13052]
### Describe the bug
Lefthook Git hook returning `executable file not found in %PATH%` when run from GitHub Desktop however does not throw error when run from Git bash

### Version & OS

Version 2.9.3

Windows 1809

### Steps to reproduce the behavior

1. Install [Lefthook](https://github.com/evilmartians/lefthook) to `PATH` & run `lefthook install`
2. Add `lefthook.yml` to repo folder as follows
   ```
   pre-commit:
     commands:
       fix-line-endings:
         glob: "*.{config}"
         run: unix2dos {staged_files}
   ```
1. Add `web.config` file to repo folder
2. Attempt to commit

### Expected behavior

pre-commit hook should run just as it does in Git Bash

### Actual behavior

pre-commit hook does not run as it does in Git Bash

### Screenshots

![image](https://user-images.githubusercontent.com/1192780/135559049-e31ed200-a063-4818-b70f-fb3da1cbf647.png)

![image](https://user-images.githubusercontent.com/1192780/135559243-96e1f2b1-18f9-46cb-9259-572f376f4970.png)

**Comment by bbodenmiller** [comment]
Hooks in GitHub desktop don't have access to `$PATH`? 🤔 

```
    path:
      glob: "*.{config}"
      run: echo $PATH
    path2:
      glob: "*.{config}"
      run: echo %PATH%
```

Results in:

![image](https://user-images.githubusercontent.com/1192780/135560034-9fa2d0ee-cc9f-4e68-b827-bf1b65603ea2.png)
