### ISSUE TITLE
Pre-commit hooks executables not found

### ISSUE THREAD

**Issue by mikeweltevrede** [desktop/desktop#15872]
### The problem

I am trying to commit but none of my pre-commit hooks seem to be found (see image). I have run `pip install` for the following file in both the virtual environment for my repo as well as outside, but neither works. Committing via Git Bash works fine

My `pre-commit-requirements.txt` file:
```
pre-commit==2.20.0
black==22.8.0
flake8==5.0.4
isort==5.10.1
```

My `.pre-commit-config.yaml` file:
```
repos:
  - repo: local
    hooks:
      - id: black
        name: Run black
        entry: black
        language: python
        args: ["--line-length=120"]
        files: ^src/.*\.py$

      - id: flake8
        name: Run flake8
        entry: flake8
        language: python
        args: ["--max-line-length=120", "--ignore=E203"]
        language_version: python3
        files: ^src/.*\.py$

      - id: isort
        name: Run isort
        entry: isort
        language: python
        language_version: python3
        files: ^src/.*\.py$
        args: ["--profile", "black"]

      - id: check-yaml
        name: yaml check
        entry: check-yaml
        language: python
        files: ^(.*yaml$|.*yml$)

      - id: name-tests-test
        name: test file name checker
        entry: name-tests-test
        language: python
        files: tests/unit/.*.py$

      - id: requirements-txt-fixer
        name: requirement text package sort
        entry: requirements-txt-fixer
        language: python
        files: .*requirements.txt$
```

Image - this error happens for all five:
![image](https://user-images.githubusercontent.com/46759318/210829830-63011b6a-6976-496b-a3d8-d8fa15949e0e.png)

### Release version

3.1.3

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Create pre-commit hooks config as in `.pre-commit-config.yaml`
2. Install libraries `pre-commit-requirements.txt`
3. Run `pre-commit install`
4. Do some changes affected by the pre-commit hooks
5. Try to commit the changes in Github Desktop

### Log files

```
2023-01-05T16:13:15.665Z - info: [ui] [Timing] Action 'create commit' for '(Repo name redacted)' took 2.333s
2023-01-05T16:14:14.009Z - info: [ui] Opt out reported.
2023-01-05T16:15:09.465Z - info: [ui] Executing createCommit: git commit -F - (took 5.213s)
2023-01-05T16:15:09.474Z - error: [ui] `git commit -F -` exited with an unexpected code: 1.
stderr:
Run black................................................................Failed
- hook id: black
- exit code: 1

Executable `black` not found

Run flake8...............................................................Failed
- hook id: flake8
- exit code: 1

Executable `flake8` not found

Run isort................................................................Failed
- hook id: isort
- exit code: 1

Executable `isort` not found

yaml check...............................................................Failed
- hook id: check-yaml
- exit code: 1

Executable `check-yaml` not found

test file name checker...................................................Failed
- hook id: name-tests-test
- exit code: 1

Executable `name-tests-test` not found

requirement text package sort............................................Failed
- hook id: requirements-txt-fixer
- exit code: 1

Executable `requirements-txt-fixer` not found


2023-01-05T16:15:09.475Z - info: [ui] [Timing] Action 'create commit' for '(Repo name redacted)' took 5.430s
```

### Screenshots

Image - this error happens for all five:
![image](https://user-images.githubusercontent.com/46759318/210829830-63011b6a-6976-496b-a3d8-d8fa15949e0e.png)
