### ISSUE TITLE
Pre-commit fails to find yarn when committing on v3.3.4

### ISSUE THREAD

**Issue by nefrob** [desktop/desktop#17600]
### The problem

After upgrading the desktop app to Version 3.3.4 (arm64) today I am no longer able to successfully run pre-commit due to "Executable `yarn` not found".

### Release version

v3.3.4

### Operating system

Mac

### Steps to reproduce the behavior

`.pre-commit-config.yaml`:

```yaml
...
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        language: node
        entry: yarn run prettier --cache --write
        types: [file]
        types_or: [javascript,jsx,ts,tsx,json,scss]
...
```

Other versions:

```
➜ yarn --version
3.6.1
➜ pre-commit --version
pre-commit 3.5.0
➜ asdf list
nodejs
 *18.17.1
```

I am still able to commit via  command line without issues:

```
➜ git commit -am "Test"
...
prettier.................................................................Passed
...
```

I also ran `pre-commit clean` but the error persists.

### Screenshots

<img width="621" alt="Screenshot 2023-10-20 at 12 21 24 PM" src="https://github.com/desktop/desktop/assets/25070989/1b170758-2861-4ed9-a475-1654b7ba1ddd">
