### ISSUE TITLE
Move sidebar to right side

### ISSUE THREAD

**Issue by foxt** [desktop/desktop#18645]
### The feature request

The option to move the side bar to the right side.

![image](https://github.com/desktop/desktop/assets/12257112/05677f04-ebc1-4732-85ca-8894733bb836)

### Proposed solution

Not a high priority issue, but if you're using multiple monitors, and have your secondary monitor to the left, it's easier to access things on the right side of the screen. (Also, I assume this would be better for RTL users, but I'm not one of those so I'm not sure)

### Additional context

Not sure of any deeper issues, but applying the following:

```css
#repository, #desktop-app-toolbar {
    flex-direction: row-reverse;  /* flip the layout */
}
.foldout {
    right: 0px; /* moves the "Current repository" drop down to the right */
}

#repository-sidebar {
    /* flip the border side */
    border-right: none;
    border-left: 1px solid var(--box-border-color);
}

.resizable-component .resize-handle {
    /* flip the resize grab handle */
    left: -5px;
    right: revert;
}
``` 
gets you most of the way there. The resizing is still a bit broken.
