### ISSUE TITLE
Allow vertical resizing of the summary and description panel

### ISSUE THREAD

**Issue by Chrysaloid** [desktop/desktop#18843]
### The feature request

Currently the summary and description panel has fixed height. And above it is a ton of free space (in most cases when you're committing changes to just one file). I tend to write long descriptions and would like to see them all without needing to scroll. And if I have to commit many files, I would rather scroll the files than the description.

### Proposed solution

Make the panel resizable vertically just like its parent panel is currently resizable horizontally . The description field should fill all available height. Paddings should stay the same and the height of summary field should stay fixed to one line. The height should be remembered between sessions.

**Comment by Chrysaloid** [comment]
OK, I have actually inspected the layout of the app with DevTools and I have came up with this CSS:
```css
.commit-message-component {
   flex-basis: 50%;
}
.commit-message-component .description-focus-container {
   display: flex;
   flex-direction: column;
   flex: 1;
}
.commit-message-component.with-action-bar .description-field textarea {
   min-height: 0;
   flex: 1;
}
```
It moves the height definition from `min-height` on `textarea` to `flex-basis` on `.commit-message-component` (that actually is the panel I was referring to in previous comment). Now, we can make `flex-basis` a CSS variable, add `resize-handle` component to `#repository-sidebar .panel` but vertical and add resize handler that would change the value of that variable based on the position of the `resize-handle`. That is a general plan. I might try to implement it if I'll have time.

For now, for those who want a OK-ish solution, you can edit  this file `C:\Users\<user>\AppData\Local\GitHubDesktop\app-3.4.1\resources\app\renderer.css` and just append the above CSS to it (probably tweak `flex-basis` to your liking) and restart GitHub Desktop. It should work until update overwrites this file.
